### ISSUE TITLE
sceneviewer-qml crash on scene 2382207814

### ISSUE THREAD

**Issue by duzhaokun123** [catsout/wallpaper-engine-kde-plugin#165]
**Describe the bug**<br/>
sceneviewer-qml crash on scene 2382207814

**Workshop link**<br/>
[2382207814](https://steamcommunity.com/sharedfiles/filedetails/?id=2382207814)

**System Information**
- Kde: [e.g. 5.20]
- Qt: 5.15.3
- OS: Arch Linux
- Installation Source: git

**Additional context**<br/>
```
❯ ./sceneviewer-qml --valid-layer /home/duzhaokun/.local/share/Steam/steamapps/common/wallpaper_engine/assets ~/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
INFO main looper started
INFO render looper started
INFO source: /home/duzhaokun/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
INFO gl: OpenGL version 3.1 loaded
INFO gl: OpenGL vendor string: Intel
[1]    27003 segmentation fault (core dumped)  ./sceneviewer-qml --valid-layer
```

**Comment by catsout** [comment]
I need the gdb backtrace for this, you can get from `gdb --args ./sceneviewer-qml --valid-layer ....`.  
But I think this issue is mostly caused by the low opengl version.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/171

**Comment by duzhaokun123** [comment]
tried https://github.com/catsout/wallpaper-engine-kde-plugin/commit/b4a945cd009d245369b0b582cab6990ac808df5c

crash with intel driver

```
❯ gdb --args ./sceneviewer-qml --valid-layer /home/duzhaokun/.local/share/Steam/steamapps/common/wallpaper_engine/assets ~/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./sceneviewer-qml...
(gdb) run
Starting program: /home/duzhaokun/src/wallpaper-engine-kde-plugin/src/backend_scene/standalone_view/build/sceneviewer-qml --valid-layer /home/duzhaokun/.local/share/Steam/steamapps/common/wallpaper_engine/assets /home/duzhaokun/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff26a1640 (LWP 3169)]
[New Thread 0x7fffebcad640 (LWP 3173)]
[New Thread 0x7fffe94df640 (LWP 3174)]
[New Thread 0x7fffe8caa640 (LWP 3175)]
[Thread 0x7fffe8caa640 (LWP 3175) exited]
[New Thread 0x7fffe8caa640 (LWP 3176)]
[New Thread 0x7fffdd07b640 (LWP 3177)]
INFO main looper started
[New Thread 0x7fffdc87a640 (LWP 3178)]
INFO render looper started
[New Thread 0x7fffd7fff640 (LWP 3179)]
INFO source: /home/duzhaokun/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
[New Thread 0x7fffd6dee640 (LWP 3180)]
[New Thread 0x7fffd65ed640 (LWP 3181)]
INFO gl: OpenGL version 3.1 loaded
INFO gl: OpenGL vendor string: Intel

Thread 11 "QSGRenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd65ed640 (LWP 3181)]
0x0000000000000000 in ?? ()
(gdb) 
quit
A debugging session is active.

        Inferior 1 [process 3166] will be killed.

Quit anyway? (y or n) y
```

work with nvidia driver

```
❯ prime-run gdb --args ./sceneviewer-qml --valid-layer /home/duzhaokun/.local/share/Steam/steamapps/common/wallpaper_engine/assets ~/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./sceneviewer-qml...
(gdb) run
Starting program: /home/duzhaokun/src/wallpaper-engine-kde-plugin/src/backend_scene/standalone_view/build/sceneviewer-qml --valid-layer /home/duzhaokun/.local/share/Steam/steamapps/common/wallpaper_engine/assets /home/duzhaokun/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffefc13640 (LWP 3688)]
[New Thread 0x7fffed404640 (LWP 3691)]
[New Thread 0x7fffe7fff640 (LWP 3692)]
[New Thread 0x7fffe73fe640 (LWP 3693)]
INFO main looper started
[New Thread 0x7fffe6bfd640 (LWP 3694)]
[New Thread 0x7fffe63fc640 (LWP 3695)]
INFO source: /home/duzhaokun/.local/share/Steam/steamapps/workshop/content/431960/2382207814/scene.pkg
INFO render looper started
[New Thread 0x7fffe51eb640 (LWP 3697)]
INFO gl: OpenGL version 4.6 loaded
INFO gl: OpenGL vendor string: NVIDIA Corporation
INFO gl: external tex using optimal tiling
INFO set swapchain image size: 1280x720
INFO vulkan valid layer "VK_LAYER_KHRONOS_validation" enabled
[New Thread 0x7fffe48a6640 (LWP 3698)]
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
[New Thread 0x7fffc95ff640 (LWP 3712)]
INFO vulkan device: NVIDIA GeForce GT 710
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
[New Thread 0x7fffb5fff640 (LWP 3713)]
INFO sound device inited
INFO pkg version: PKGV0011
INFO new buffer block, size: 2097152, index: 0
INFO new buffer block, size: 2097152, index: 0
wekde.scene: receive external texture(1280x720) from fd: 46
wekde.scene: receive external texture(1280x720) from fd: 45
wekde.scene: receive external texture(1280x720) from fd: 44
```

**Comment by catsout** [comment]
@duzhaokun123 
You need run `backtrace` before `quit` in gdb shell.

**Comment by duzhaokun123** [comment]
```
(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x00005555555fa86f in GlExtra::init (this=0x7fffc000ea20, 
    get_proc_address=0x5555555f4650 <(anonymous namespace)::get_proc_address(char const*)>)
    at /home/duzhaokun/src/wallpaper-engine-kde-plugin/src/backend_scene/glExtra.cpp:75
#2  0x00005555555f6a4c in scenebackend::TextureNode::initGl (this=0x7fffc000e840)
    at /home/duzhaokun/src/wallpaper-engine-kde-plugin/src/backend_scene/SceneBackend.cpp:98
#3  0x00005555555f4c07 in scenebackend::SceneObject::updatePaintNode (this=0x55555604be80, 
    oldNode=0x0)
    at /home/duzhaokun/src/wallpaper-engine-kde-plugin/src/backend_scene/SceneBackend.cpp:190
#4  0x00007ffff7c9dcb8 in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) ()
   from /usr/lib/libQt5Quick.so.5
#5  0x00007ffff7c9e4c5 in QQuickWindowPrivate::updateDirtyNodes() () from /usr/lib/libQt5Quick.so.5
#6  0x00007ffff7c8ec79 in QQuickWindowPrivate::syncSceneGraph() () from /usr/lib/libQt5Quick.so.5
#7  0x00007ffff7c3b06e in ?? () from /usr/lib/libQt5Quick.so.5
#8  0x00007ffff7c3edc4 in ?? () from /usr/lib/libQt5Quick.so.5
#9  0x00007ffff69ac36a in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff630354d in ?? () from /usr/lib/libc.so.6
#11 0x00007ffff6388b14 in clone () from /usr/lib/libc.so.6
```

do i also need install some debug package

**Comment by catsout** [comment]
> do i also need install some debug package

No, this is enough.

**Comment by catsout** [comment]
@duzhaokun123 
Please test the new commit.

**Comment by duzhaokun123** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/commit/16333ca8bd90e8e70eaad9e709988d3b2f584b91 work with intel driver
