### ISSUE TITLE
broken on plasma 5.25.4 when reconfiguring monitors (changing position primary etc)

### ISSUE THREAD

**Issue by zany130** [catsout/wallpaper-engine-kde-plugin#218]
**Describe the bug**<br/>
after reconfiguring monitors (changing position primary etc)
plugin causes system hangs when interacting with the desktop and other issues (black screens broken wallpaper selection (just says python error)

**System Information**
Operating System: Garuda Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.16-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

- Installation Source: chaotic aur package version 0.5.4-1

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
worked fine on plasma 5.25.3

here is an image of the broken wallpaper selector
![image](https://user-images.githubusercontent.com/25832539/184052893-21388d77-b52c-4afd-bf8f-c33078202f09.png)

noticed there is a lot of `Garuda-Linux plasmashell[70237]: qml: time out` and `qml: folder not found: /home/zany130/.local/share/Steam/steamapps/common/wallpaper_engine/projects/myprojects` messages in my journel

**Comment by catsout** [comment]
What's the output of `python3 /usr/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py`

**Comment by zany130** [comment]
```
python3 /usr/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py
usage: pyext.py [-h] URL
pyext.py: error: the following arguments are required: URL
```

**Comment by zany130** [comment]
may have be a `.cache` issue. will leave open for a day or two to confirm but can no longer reproduce any of the issues mentioned above

**Comment by zany130** [comment]
Seems like it was a cache issue haven't been able to reproduce since

**Comment by zany130** [comment]
was able to reproduce again seems like it not related to reconfiguring monitors as it happened with me just using my computer normally.

clearing the cache fixes it for awhile so it seems like its an issue with the cache?

**Comment by catsout** [comment]
```py
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
  message = await self.read_message()
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
  frame = await self.read_data_frame(max_size=self.max_size)
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
  frame = await self.read_frame(max_size)
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
  frame = await Frame.read(
File "/usr/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
  data = await reader(2)
File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
  await self._wait_for_data('readexactly')
File "/usr/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
  await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 168, in <module>
  asyncio.run(connect(args["url"]))
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
  return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
  return future.result()
File "/usr/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 155, in connect
  recv = jrpc.handle(await websocket.recv())
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
  await self.ensure_open()
File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
  raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
```  

No idea, I can't reproduce.

**Comment by zany130** [comment]
yeah I can't even really tell how to reproduce this it seems so random happened to me twice yesterday. if I find anything I'll report back.

basically the whole kde desktop seems to hang  (just the desktop and the widgets on it latte dock and other applications continue to work)

**Comment by Bungeetaco** [comment]
Had the same issue, which was able to resolve by clearing the shader cache located at ~/.cache/wescene-renderer/ & removing the WallpaperSource line as described in this issue reply: [https://github.com/catsout/wallpaper-engine-kde-plugin/issues/182#issuecomment-1143130373](url)

**Comment by zany130** [comment]
yeah like I said the fixes it for a while and then it comes back

**Comment by zany130** [comment]
so tried switching to X to see if this is a Wayland issue. Still happens on x here is a new log https://gist.github.com/zany130/4f2a8a213c3014d8ddf65dbe4b133f06

I'm thinking it might be related to https://github.com/catsout/wallpaper-engine-kde-plugin/issues/189 ass this happened after my display turned off for sleep @catsout
