### ISSUE TITLE
I did all step by step in instruction(3x times). At finish i installed WallPaper engine in steam and Proton 7.0. But i still can't solve error when try to set up path with wallpapers. I get this error:

### ISSUE THREAD

**Issue by GHNuma** [catsout/wallpaper-engine-kde-plugin#245]
**Describe the bug**<br/>

**Workshop link**<br/>
[e.g. 1139304621](https://steamcommunity.com/sharedfiles/filedetails/?id=1139304621)

**System Information**
- Kde: [e.g. 5.20]
- Qt: [e.g. 5.15]
- OS: [e.g. Debian]
- Installation Source: [e.g. KDE Plugins or git]

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]

**Comment by GHNuma** [comment]
Python helper run failed:
Traceback (most recent call last):
File "/home/nurmukhamed/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 168, in <module>
asyncio.run(connect(args["url"]))
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
FIle "/usr/lib/python3.10/asyncio/base_events/py", line 646, in run_until_complete
return future.result()
File "/home/nurmukhamed/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 153, in connect
async with websockets.connect(uri) as websocket:
FIle "/usr/lib.python3/dist-packages/websockets/legacy/client.py", line 604, in __aenter__
return await self
File "/usr/lib/python3/dist-packages/websockets/legacy/client.py", line 622, in __await_impl__transport, protocol = await self._create_connection()
File "/usr/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection transport, protocol = await self._create_connection_transport(
File "/usr/lib/python3.10/asyncio/base_events.py", line 1107, in _create_connection_transport
protocol = protocol_factory())
File "/usr/lib/python3/dist-packages/websockets/legacy/client.py", line 160, in __init__ super().__init__(**kwargs)
File "/usr/lib/python3/dist_packages/websockets/legacy/protocol.py", line 154, in __init__ self._drain_lock = asyncio.Lock(
FIle "/usr/lib/python3.10/asyncio/locks.py", line 78, in __init__ super().__init__(loop=loop)
File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__ raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary))

**Comment by GHNuma** [comment]
KDE Plasma: 5.24.6
Qt:5.15.3
OS:Ubuntu
Installation Source: git
![Screenshot_20221021_152118](https://user-images.githubusercontent.com/91706729/197166491-50d48a04-70a0-4d8a-a045-2b76cdf5204b.png)

**Comment by GHNuma** [comment]
![Screenshot_20221021_154557](https://user-images.githubusercontent.com/91706729/197167009-eb16b0ee-d195-4c0c-97e1-d3328edff4b6.png)

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162
