### ISSUE TITLE
pyext.py quit unexpectedly

### ISSUE THREAD

**Issue by CorneliusCornbread** [catsout/wallpaper-engine-kde-plugin#351]
**Describe the bug**<br/>
Randomly while using my desktop display driver will crash, pointing to Wallpaper engine as the culprit

**Workshop link**<br/>
Private custom wallpaper, N/A

**System Information**
- Kde: 5.27.10
- Qt: 5.15.11
- OS: Fedora 39
- Installation Source: git
- Wallpaper Engine version: 2.3.26

**Additional context**<br/>
```
protocol.py:935:ensure_open:websockets.exceptions.ConnectionClosedError: no close frame received or sent

Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/streams.py", line 747, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jack/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 168, in <module>
    asyncio.run(connect(args["url"]))
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jack/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py", line 155, in connect
    recv: str = jrpc.handle(await websocket.recv())
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib64/python3.12/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

Local variables in innermost frame:
self: <websockets.legacy.client.WebSocketClientProtocol object at 0x7fa111a744d0>
```

**Comment by CorneliusCornbread** [comment]
Newest update to Mesa seems to have resolved this? Closing for now
